export const PLANS = [
  {
    id: 1,
    monthlySubscriptionId: 'P-8NR351201R606522SMI5EGOA',
    yearlySubscriptionId: 'P-6VD21250SY8489504MJBUAWA',
    title: 'Lite',
    price: 2.99,
    yearlyPrice: 23.99,
    label: 'Recommended',
    backgroundColorCode: '#FFFFFF',
    borderBottomColor: '#2D3435',
    priceBgColor: '#14C68E24',
    enableIcon: 'blue-circle.png',
    disableIcon: 'disable-icon.png',
    features: [
      {id: 'ft-1', description: 'Dashboard View', isDisabled: false},
      {id: 'ft-2', description: 'Net Worth Projection', isDisabled: false},
      {id: 'ft-3', description: 'Emergency Plan', isDisabled: false},
      {id: 'ft-4', description: 'Past Transactions', isDisabled: false},
      {
        id: 'ft-5',
        description: 'Review Future Transactions',
        isDisabled: false,
      },
      {
        id: 'ft-6',
        description: 'Planning Debt Management',
        isDisabled: false,
      },
      {id: 'ft-7', description: 'Budget Insights', isDisabled: false},
      {id: 'ft-8', description: 'Wishlist Management', isDisabled: false},
      {id: 'ft-9', description: 'Collaboration Templates', isDisabled: false},
      {id: 'ft-10', description: 'Bank Account Sync', isDisabled: true},
      {
        id: 'ft-11',
        description: 'Retirement & Debt Accounts Sync',
        isDisabled: true,
      },
      {id: 'ft-12', description: '5 Sub-account Users', isDisabled: true},
    ],
  },

  {
    id: 2,
    monthlySubscriptionId: 'P-63B846608W5333833MJBULKI',
    yearlySubscriptionId: 'P-16H532184C012360EMJBUMII',
    title: 'Premium',
    price: 4.99,
    yearlyPrice: 45.99,
    label: 'Best value',
    backgroundColorCode: '#096674',
    fontColor: '#FFFFFF',
    borderBottomColor: '#0A5560',
    priceBgColor: '#FFFFFF1A',
    enableIcon: 'white-circle.png',
    disableIcon: 'white-disable-icon.png',
    features: [
      {id: 'ft-1', description: 'Dashboard View', isDisabled: false},
      {id: 'ft-2', description: 'Net Worth Projection', isDisabled: false},
      {id: 'ft-3', description: 'Emergency Plan', isDisabled: false},
      {id: 'ft-4', description: 'Past Transactions', isDisabled: false},
      {
        id: 'ft-5',
        description: 'Review Future Transactions',
        isDisabled: false,
      },
      {
        id: 'ft-6',
        description: 'Planning Debt Management',
        isDisabled: false,
      },
      {id: 'ft-7', description: 'Budget Insights', isDisabled: false},
      {id: 'ft-8', description: 'Wishlist Management', isDisabled: false},
      {id: 'ft-9', description: 'Collaboration Templates', isDisabled: false},
      {id: 'ft-10', description: 'Bank Account Sync', isDisabled: false},
      {
        id: 'ft-11',
        description: 'Retirement & Debt Accounts Sync',
        isDisabled: false,
      },
      {id: 'ft-12', description: '5 Sub-account Users', isDisabled: true},
    ],
    subscriptionDetail: {
      id: 'P-08C26376J16051935MEZV6DI',
      name: 'Premium',
      price: 4.99,
    },
  },
  {
    id: 3,
    monthlySubscriptionId: 'P-6H485698EE616300EMJBUNGY',
    yearlySubscriptionId: 'P-7MV174874A0934120MJBUN6Q',
    title: 'Family',
    price: 5.99,
    yearlyPrice: 54.99,
    label: '',
    backgroundColorCode: '#0D0D0D',
    fontColor: '#FFFFFF',
    borderBottomColor: '#0A5560',
    priceBgColor: '#FFFFFF1A',
    enableIcon: 'white-circle.png',
    disableIcon: 'disable-icon.png',
    features: [
      {id: 'ft-1', description: 'Dashboard View', isDisabled: false},
      {id: 'ft-2', description: 'Net Worth Projection', isDisabled: false},
      {id: 'ft-3', description: 'Emergency Plan', isDisabled: false},
      {id: 'ft-4', description: 'Past Transactions', isDisabled: false},
      {
        id: 'ft-5',
        description: 'Review Future Transactions',
        isDisabled: false,
      },
      {
        id: 'ft-6',
        description: 'Planning Debt Management',
        isDisabled: false,
      },
      {id: 'ft-7', description: 'Budget Insights', isDisabled: false},
      {id: 'ft-8', description: 'Wishlist Management', isDisabled: false},
      {id: 'ft-9', description: 'Collaboration Templates', isDisabled: false},
      {id: 'ft-10', description: 'Bank Account Sync', isDisabled: false},
      {
        id: 'ft-11',
        description: 'Retirement & Debt Accounts Sync',
        isDisabled: false,
      },
      {id: 'ft-12', description: '5 Sub-account Users', isDisabled: false},
    ],
  },
];
